---
- hosts: all
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes
        force_apt_get: yes
        become_method: sudo

    - name: Upgrade packages
      apt:
        upgrade: present
        force_apt_get: yes
        become_method: sudo

    - name: Upgrade pihole
      command: pihole -up
