---
- hosts: all 
  become: yes
  tasks:
    - name: upgrade pihole
      command: pihole -up

    - name: update packages
      apt:
        update_cache: yes

    - name: upgrade packages
      apt:
        state: present
