---
- hosts: all 
  become: yes
  tasks:
    - name: update packages
      apt:
        update_cache: yes

    - name: upgrade packages
      apt:
        name: "*"
        state: latest

    - name: upgrade dist
      apt:
        upgrade: dist
